# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: release
name: Duplicate Release With Asset to public_Repo

jobs:
  Checkout:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        path: 'TestReleaseGitAction'
        ref: 'main'
        repository: 'ablack3/TestReleaseGitAction'
        token: ${{ secrets.PRIVATE_TOKEN }}
        persist-credentials: true

  Push:
    - name: Push private to public
      shell: bash
      working-directory: 'TestReleaseGitAction'
      run: |
        git config --global user.name "release bot"
        git remote add public git@github.com:ablack3/TestReleaseGitActionPublic
        git push public main

  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: Hs1r1us/Release-AIO@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
        with:
          tag_name: 'inherit' # Must use 'inherit' to get the latest release
          body: 'hello world' # Will be added in the new release
          repo: 'ablack3/TestReleaseGitActionPublic' # The format is like owner/repo
          # asset_files: './asset_file' # Will be added in the new release

