# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on: push
name: Duplicate Release With Asset to public_Repo

jobs:
  Mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: 'TestReleaseGitAction'
          ref: 'main'
          repository: 'darwin-eu/TestReleaseGitAction'
          token: ${{ secrets.PRIVATE_TOKEN }}
          persist-credentials: true

      - name: Push to public mirror
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
        shell: bash
        working-directory: 'TestReleaseGitAction'
        # git remote add public git@github.com:ablack3/TestReleaseGitActionPublic
        # eval 'git pull https://$GITHUB_TOKEN@github.com/ablack3/TestReleaseGitActionPublic.git main'
        run: |
          git config --global user.name "release bot"
          git config --global pull.ff only
          eval 'git pull https://$GITHUB_TOKEN@github.com/darwin-eu-dev/TestReleaseGitActionPublic.git main'
          git push origin main

#
      # - uses: Hs1r1us/Release-AIO@v2.0.0
      #   env:
      #       GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
      #   with:
      #     tag_name: 'inherit' # Must use 'inherit' to get the latest release
      #     body: 'hello world' # Will be added in the new release
      #     repo: 'darwin-eu/TestReleaseGitAction' # The format is like owner/repo
      #     # asset_files: './asset_file' # Will be added in the new release

