# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  release:
    branches: [main, master]

name: Duplicate Release With Asset to public_Repo

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: Hs1r1us/Release-AIO@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
        with:
          tag_name: 'inherit' # Must use 'inherit' to get the latest release
          body: 'hello world' # Will be added in the new release
          repo: 'ablack3/TestReleaseGitActionPublic' # The format is like owner/repo
          asset_files: './asset_file' # Will be added in the new release

